### PR TITLE
Added the copyright declarations.

### PR DESCRIPTION
**Pull request by hopeseekr**
You might really want to consider using a permissive license, such as the MIT License.

As it stands now, no one can do anything with this project except read it.

### CODE REVIEW

**Comment by healthlabs-bugman** [comment]
Paging @joshmedeski to review the testing work in this pull request!

**Comment by healthlabs-bugman** [comment]
Paging @JacobStarfish to review the front-end work in this pull request!

**Comment by Chekote** [comment]
That is the intended license for this. We made it public to allow other teams to access the code, but it is not a public project in the sense that we are courting outside contributors. Thanks for the heads up though.

**Comment by hopeseekr** [comment]
@Chekote You really want the copyright declarations with "All rights reserved" added to the source code files then... This PR should be merged. I recommend you seek advice w/ legal if you doubt this.

**Pull request closed without merging**
