### PR TITLE
Removing changelog

### PR DESCRIPTION
**Pull request by ramsey-medology**

### CODE REVIEW

**Comment by healthlabs-bugman** [comment]
Testing file changes were not found.
Paging @Chekote to review the back-end work in this pull request!
Paging @johnnie502 to review the testing work in this pull request!

I couldn't recognize who these files were relevant to:
CHANGELOG.md

**Comment by Chekote** [comment]
I've never understood why we would have a changelog file on a project hosted on Github. We already have the [releases](https://github.com/Medology/findalab/releases) section on the project's page, and we can easily see a changelog for each release by using Github's compare feature. e.g. [2.8.11 - 2.8.22](https://github.com/Medology/findalab/compare/2.8.21...2.8.22).

How do you feel about just deleting this file?

**Comment by ramsey-medology** [comment]
@Chekote  I agree with removing to eliminate the redundancy. I'll make the changes to the PR and then update the release once it's been merged.

**Comment by healthlabs-bugman** [comment]
Paging @fortoulrodolfo to review the front-end work in this pull request!

I couldn't recognize who these files were relevant to:
CHANGELOG.md

**Pull request merged**
